use crate::reinterpret::OriginalAlloc;
use crate::{Ptr, Value};
use std::cell::{Ref, RefMut};
use std::rc::Rc;

/// Allows extending Ptr through the autogenerated.rs file. Required methods have no
/// default, opt-in methods panic by default and are overridden by seams that support
/// them.

pub trait PtrSeam<T> {
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool;
    fn address(&self) -> usize;
    fn upgrade(&self, offset: usize) -> Box<dyn StrongPtrSeam<T>>;

    /// Opt-in, enables Ptr::reinterpret_cast.
    fn as_original_alloc(&self, _offset: usize) -> Rc<dyn OriginalAlloc> {
        panic!("reinterpret_cast is not supported by this seam")
    }

    /// Opt-in, enables Ptr::sort_with_cmp.
    fn sort_with_cmp(
        &self,
        _from: usize,
        _last: usize,
        _cmp: &mut dyn FnMut(Ptr<T>, Ptr<T>) -> bool,
    ) {
        panic!("sort_with_cmp is not supported by this seam")
    }

    /// Opt-in, enables Ptr::sort.
    fn sort(&self, _from: usize, _last: usize)
    where
        T: Ord,
    {
        panic!("sort is not supported by this seam")
    }

    /// Opt-in, enables Ptr<u8>::with_slice.
    fn with_slice(&self, _offset: usize, _len: usize, _f: &mut dyn FnMut(&[u8])) {
        panic!("with_slice is not supported by this seam")
    }

    /// Opt-in, enables Ptr<u8>::with_slice_mut.
    fn with_slice_mut(&self, _offset: usize, _len: usize, _f: &mut dyn FnMut(&mut [u8])) {
        panic!("with_slice_mut is not supported by this seam")
    }

    /// Opt-in, enables Ptr::delete.
    fn delete(&self, _offset: usize) {
        panic!("delete is not supported by this seam")
    }

    /// Opt-in, enables Ptr::delete_array.
    fn delete_array(&self, _offset: usize) {
        panic!("delete_array is not supported by this seam")
    }

    /// Opt-in, enables Ptr::to_strong.
    fn to_strong(&self, _offset: usize) -> Value<T> {
        panic!("to_strong is not supported by this seam")
    }

    /// Opt-in: enables Ptr::to_owned_opt.
    fn to_owned_single(&self, _offset: usize) -> Option<Value<T>> {
        panic!("to_owned_single is not supported by this seam")
    }

    /// Opt-in: enables Ptr::to_owned_opt.
    fn to_owned_array(&self, _offset: usize) -> Option<Value<Box<[T]>>> {
        panic!("to_owned_array is not supported by this seam")
    }
}

pub trait StrongPtrSeam<T> {
    fn deref(&self) -> Ref<'_, T>;
    fn deref_mut(&self) -> RefMut<'_, T>;
}

pub trait PtrDynSeam<T: ?Sized> {
    fn upgrade(&self, offset: usize) -> Box<dyn StrongPtrDynSeam<T>>;
}

impl<T: ?Sized> std::fmt::Debug for dyn PtrDynSeam<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Seam")
    }
}

pub trait StrongPtrDynSeam<T: ?Sized> {
    fn deref(&self) -> Ref<'_, T>;
    fn deref_mut(&self) -> RefMut<'_, T>;
}

#[cfg(test)]
mod tests {
    use crate::{AsPointer, Ptr, PtrSeam, StrongPtrSeam, Value};
    use std::cell::{Ref, RefCell, RefMut};
    use std::rc::{Rc, Weak};

    struct Seg<T>(Vec<T>);

    impl<T: 'static> PtrSeam<T> for Weak<RefCell<Seg<T>>> {
        fn len(&self) -> usize {
            Weak::upgrade(self)
                .expect("ub: dangling pointer")
                .borrow()
                .0
                .len()
        }

        fn is_empty(&self) -> bool {
            Weak::upgrade(self)
                .expect("ub: dangling pointer")
                .borrow()
                .0
                .is_empty()
        }

        fn address(&self) -> usize {
            self.as_ptr() as usize
        }

        fn upgrade(&self, offset: usize) -> Box<dyn StrongPtrSeam<T>> {
            Box::new((Weak::upgrade(self).expect("ub: dangling pointer"), offset))
        }
    }

    impl<T> StrongPtrSeam<T> for (Rc<RefCell<Seg<T>>>, usize) {
        fn deref(&self) -> Ref<'_, T> {
            let i = self.1;
            Ref::map(self.0.borrow(), move |c| &c.0[i])
        }

        fn deref_mut(&self) -> RefMut<'_, T> {
            let i = self.1;
            RefMut::map(self.0.borrow_mut(), move |c| &mut c.0[i])
        }
    }

    impl<T: 'static> AsPointer<T> for Rc<RefCell<Seg<T>>> {
        fn as_pointer(&self) -> Ptr<T> {
            Ptr::seam(Rc::new(Rc::downgrade(self)))
        }
    }

    fn seg(v: Vec<i32>) -> Value<Seg<i32>> {
        Rc::new(RefCell::new(Seg(v)))
    }

    #[test]
    fn seam_len() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        assert_eq!(ptr.len(), 3);
        assert!(!ptr.is_empty());
    }

    #[test]
    fn seam_elements() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        assert_eq!(ptr.with(|v| *v), 1);
        let back: Ptr<i32> = &ptr + 2;
        assert_eq!(back.with(|v| *v), 3);
    }

    #[test]
    fn seam_with_mut() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        ptr.with_mut(|v| *v = 10);
        assert_eq!(ptr.with(|v| *v), 10);
    }

    #[test]
    fn seam_pointer() {
        let seam = seg(vec![1, 2, 3]);
        let ptr1: Ptr<i32> = seam.as_pointer();
        let ptr2: Ptr<i32> = seam.as_pointer();
        assert_eq!(ptr1, ptr2);

        let ptr3 = &ptr1 + 1;
        assert_ne!(ptr1, ptr3);
        assert!(ptr3 > ptr1);
        assert_eq!(ptr3 - ptr1, 1);
    }

    #[test]
    #[should_panic(expected = "dangling")]
    fn seam_dangling_ptr() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        drop(seam);
        let _ = ptr.len();
    }

    #[test]
    #[should_panic(expected = "not supported by this seam")]
    fn seam_reinterpret_cast_panics() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        let _ = ptr.reinterpret_cast::<u8>();
    }

    #[test]
    #[should_panic(expected = "not supported by this seam")]
    fn seam_sort_panics() {
        let seam = seg(vec![3, 1, 2]);
        let ptr: Ptr<i32> = seam.as_pointer();
        ptr.sort(3);
    }

    #[test]
    #[should_panic(expected = "not supported by this seam")]
    fn seam_delete_panics() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        ptr.delete();
    }

    #[test]
    #[should_panic(expected = "not supported by this seam")]
    fn seam_to_strong_panics() {
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        let _ = ptr.to_strong();
    }

    #[test]
    #[should_panic(expected = "not supported by this seam")]
    fn seam_to_owned_panics() {
        use crate::ToOwnedOption;
        let seam = seg(vec![1, 2, 3]);
        let ptr: Ptr<i32> = seam.as_pointer();
        let _: Option<Value<i32>> = ptr.to_owned_opt();
    }
}
