[package]
name = "rule-preprocessor"
version = "0.1.0"
edition = "2024"

[dependencies]
libcc2rs = { path = "../libcc2rs" }
cfg-expr = "0.20"
ra_ap_syntax = "0.0.266"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = { version = "0.2", optional = true }
brotli-sys = { version = "0.3", optional = true }

[features]
default = ["libc", "brotli-sys"]
